### ISSUE TITLE
PaddingByteInformationDisclosure reports false pasitive

### ISSUE THREAD

**Issue by pmisik** [microsoft/Windows-Driver-Developer-Supplemental-Tools#11]
In order to satisfy cpp/windows/wdk/deprecated-api we replaced
`ExAllocatePoolWithTag` by `ExAllocatePoolZero` and declared macro POOL_ZERO_DOWN_LEVEL_SUPPORT for compilation as code must run downlevel.

However memory is zeroed during allocation now we see false positive
`Warning SM02320: Memory allocation of [MyStruct](1) includes uninitialized padding bytes.`

Here is example of code

```
typedef enum { Unknown = 0, Known = 1, Other = 2 } MyStructType;
struct MyStruct { MyStructType type; UINT64 id; };
MyStruct* testReturn()
{
	MyStruct* myBadStackStruct = (MyStruct*)ExAllocatePoolZero(NonPagedPool, sizeof(MyStruct), 'MSFT');
	return myBadStackStruct;
}
```

**Comment by NateD-MSFT** [comment]
I missed the notice for this; thanks for bringing it to our attention.
