### ISSUE TITLE
Install pack using codeql 2.4.6

### ISSUE THREAD

**Issue by bormaa** [microsoft/Windows-Driver-Developer-Supplemental-Tools#67]
Accorrding to docs if you are using Windows Server 2022 it is better to use codeql 2.4.6
but in the stage number 5 which refer to install the pack it fails because codeql before v2.6.0 doesn't support pack installing

**Comment by lauragonzalezzz** [comment]
Hi @bormaa, thank you so much for pointing this out. You are totally correct.
In order to use 2.4.6 you will need to use the command `git clone --recurse-submodules` and disregard the pack installation method.
Feel free to reopen if you have any more questions.
Thank you!
