### ISSUE TITLE
Referenced pack not found

### ISSUE THREAD

**Issue by eddsanity** [microsoft/Windows-Driver-Developer-Supplemental-Tools#76]
I was following the quickstart section of the readme and at step 7 (analyzing the codeQL database), I get the following failure.
```sh
$ ./codeql database analyze ../DriverDatabase --format=sarifv2.1.0 --output=../DriverAnalysis1.sarif ../Windows-Driver-Developer-Supplemental-Tools/src/suites/windows_driver_mustfix.qls
Running queries.
ERROR: Referenced pack 'codeql/cpp-all' not found. (C:\Users\Eyad\.codeql\packages\codeql\cpp-queries\0.2.0\qlpack.yml:1,1-1)
ERROR: Referenced pack 'codeql/suite-helpers' not found. (C:\Users\Eyad\.codeql\packages\codeql\cpp-queries\0.2.0\qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for C:\Users\Eyad\.codeql\packages\codeql\cpp-queries\0.2.0
```

Up until that steps, every step was successful. I checked for the existence of `codeql/cpp-all` and `codeql/suite-helpers` myself and they do in fact exist at `C:\Users\Eyad\.codeql\packages\codeql\`, which has `cpp-all`, `cpp-queries` and `suite-helpers` in it (and nothing else).

I use the v2.6.3 binaries.

Any ideas?

EDIT: Update: I tried redoing the entire quickstart guide but using the binaries corresponding to latest / main and it worked fine. What gives?

**Comment by lauragonzalezzz** [comment]
Hi @eddsanity, thank you for reaching out, apologies for the confusion.
CodeQL CLI went through a big update between v2.6 and v2.11 when they began using QL packs for queries which means a whole different repo structure. The branches WHCP_22H2 and WHCP_22H1 use CodeQL CLI v2.6 and v2.4 which mean they don't use the QL packs, but MAIN uses v2.11 which does have the QL packs. The branches have different installation instructions which can be confusing but they must all be maintained for posterity with WHCP updates. I have a PR out which indicates this change, and it was just approved so it will be merged shortly. My apologies for you hitting this issue before I could get that clarification out.
Are you able to use the main branch setup for your purposes or are you certifying with WHCP?

**Comment by eddsanity** [comment]
Hey @lauragonzalezzz, don't worry about it. Yes, I am working on an AV driver (so a software driver), but as far as I understand it we are required to certify with WHCP to be able to sign and deploy the driver. It is all still in prototype phase so I may be wrong on that and I would totally appreciate being corrected on it if I am wrong (if software drivers don't need to certify with WHCP)

**Comment by Cymoki** [comment]
Hi @eddsanity, is there a particular driver type/area this software driver is associated with? 
WHCP does handle some user-mode/software drivers like Anti-malware and printers, understanding this will help answer the question of applicability.
