### ISSUE TITLE
StaticToolsLogo test : DVL file format incorrect, using branch WHPC 21H2

### ISSUE THREAD

**Issue by ALKG7** [microsoft/Windows-Driver-Developer-Supplemental-Tools#81]
I am doing StaticToolsLogo Test, using CodeQL CLI v2.4.6 and Windows-Driver-Developer-Supplemental-Tools (branch WHPC 21H2).
After put log file into C:\DVL\***.DVL.XML, I got test error information :
DVL test failed:
DVL file format incorrect(***.x64.Semmle.Summary).

Is it because my HLK version is too old to recognize the DVL file format？
Which branch should i use, to pass StaticToolsLogo test in HLK (VHLK) for Windows 10, version 2004 ?
_______________________________________________

My HLK enviroment is: 
HLK version:Virtual HLK (VHLK) for Windows 10, version 2004 
driver works on :Windows 10, version 21H2

My develop enviroment is:
VS2022
Windows 11, version 22H2 WDK(10.0.22621.382)
Windows 11, version 22H2 SDK(10.1.22621.755)

**Comment by Cymoki** [comment]
Hello, 
The versions of HLK and the DVL.exe from the WDK should match. In this scenario the older HLK test doesn't recognize the newer DVL log output. Please use either the WDK or Ewdk for Windows 10, version 2004. Both can be obtained from here:
https://learn.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads

**Comment by SanderVanDenBerk** [comment]
Hello, I have the same issue. But how can I check if the DVL and HLK are matching?

**Comment by ALKG7** [comment]
Use the latest HLK environment will solve this problem. For example, I used win11 22h2. 
















At 2023-12-29 16:00:49, "Sander van den Berk" ***@***.***> wrote:

Hello, I have the same issue. But how can I check if the DVL and HLK are matching?
