### ISSUE TITLE
CodeQL 2.6.3 is incompatible with VS 17.8

### ISSUE THREAD

**Issue by matlimatli** [microsoft/Windows-Driver-Developer-Supplemental-Tools#98]
There is a compatibility issue with the latest release of Visual Studio and CodeQL. The issue will be fixed in CodeQL 2.15.4. Refer to https://github.com/github/codeql/issues/14927 for details.

That fix will however not help in the WHCP case, where only CodeQL 2.6.3 is supported.

**Comment by jacob-ronstadt** [comment]
@matlimatli CodeQL 2.15.4 has been validated for use with WHCP. Please refer to the updated readme file in the main branch.
